#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

only=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --only)
      only="${2:-}"
      [[ -n "$only" ]] || die "--only requires a repository name"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage: scripts/fetch-upstreams.sh [--only NAME]

Fetches upstream repositories into build/src and writes source manifests.
Set SPX_GIT_DEPTH=0 to fetch full Git history instead of shallow refs.

Repository names:
  kernel
  aarch64-kernel-configs
  aarch64-firmware
  aarch64-packages
  aarch64-arch-mkimg
  grub-image-aarch64
EOF
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

fetch_one() {
  local name="$1"
  local url="$2"
  local ref="$3"
  if [[ -n "$only" && "$only" != "$name" ]]; then
    return 0
  fi
  clone_or_update "$name" "$url" "$ref"
}

ensure_dir "$SPX_SRC_DIR" "$SPX_MANIFEST_DIR"

fetch_one kernel "$SPX_KERNEL_REPO" "$SPX_KERNEL_REF"
fetch_one aarch64-kernel-configs "$SPX_CONFIG_REPO" "$SPX_CONFIG_REF"
fetch_one aarch64-firmware "$SPX_AARCH64_FIRMWARE_REPO" "$SPX_AARCH64_FIRMWARE_REF"
fetch_one aarch64-packages "$SPX_AARCH64_PACKAGES_REPO" "$SPX_AARCH64_PACKAGES_REF"
fetch_one aarch64-arch-mkimg "$SPX_ARCH_MKIMG_REPO" "$SPX_ARCH_MKIMG_REF"
fetch_one grub-image-aarch64 "$SPX_GRUB_IMAGE_REPO" "$SPX_GRUB_IMAGE_REF"

manifest_md="${SPX_MANIFEST_DIR}/source-lock.md"
manifest_env="${SPX_MANIFEST_DIR}/source-lock.env"

{
  printf '# Source Lock\n\n'
  printf 'Generated: %s\n\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf '| Name | Ref | Commit | URL |\n'
  printf '| --- | --- | --- | --- |\n'
  for row in \
    "kernel|${SPX_KERNEL_REF}|${SPX_KERNEL_REPO}" \
    "aarch64-kernel-configs|${SPX_CONFIG_REF}|${SPX_CONFIG_REPO}" \
    "aarch64-firmware|${SPX_AARCH64_FIRMWARE_REF}|${SPX_AARCH64_FIRMWARE_REPO}" \
    "aarch64-packages|${SPX_AARCH64_PACKAGES_REF}|${SPX_AARCH64_PACKAGES_REPO}" \
    "aarch64-arch-mkimg|${SPX_ARCH_MKIMG_REF}|${SPX_ARCH_MKIMG_REPO}" \
    "grub-image-aarch64|${SPX_GRUB_IMAGE_REF}|${SPX_GRUB_IMAGE_REPO}"
  do
    IFS='|' read -r name ref url <<< "$row"
    repo_dir="$(repo_path_for "$name")"
    if [[ -d "${repo_dir}/.git" ]]; then
      printf '| `%s` | `%s` | `%s` | %s |\n' "$name" "$ref" "$(git_head "$repo_dir")" "$url"
    fi
  done
} > "$manifest_md"

{
  printf '# Generated by scripts/fetch-upstreams.sh\n'
  for row in \
    "SPX_KERNEL_COMMIT|kernel" \
    "SPX_CONFIG_COMMIT|aarch64-kernel-configs" \
    "SPX_AARCH64_FIRMWARE_COMMIT|aarch64-firmware" \
    "SPX_AARCH64_PACKAGES_COMMIT|aarch64-packages" \
    "SPX_ARCH_MKIMG_COMMIT|aarch64-arch-mkimg" \
    "SPX_GRUB_IMAGE_COMMIT|grub-image-aarch64"
  do
    IFS='|' read -r key name <<< "$row"
    repo_dir="$(repo_path_for "$name")"
    if [[ -d "${repo_dir}/.git" ]]; then
      printf '%s=%s\n' "$key" "$(git_head "$repo_dir")"
    fi
  done
} > "$manifest_env"

info "Wrote ${manifest_md}"
info "Wrote ${manifest_env}"
